carracing_config = {
    "env_type": "carracing",
    "num_seeds": 8,
    "n_repeat": 8,
    "n_envs": 16,
    "train_steps": 1_500_000,
    "eval_interval": 10_000 * 16,
    "num_init_states": 8,
    "eval_episodes": 16,
    "near_optimal_score": 8.5,
    "sub_optimal_score": 7.5,
    "save_path": "./carracing_mapseed_results",
}

# lunarlander_config = {
#     "env_type": "lunarlander",
#     "num_densities": 3,
#     "density_start": 3.0,
#     "density_stop": 7.0,
#     "n_repeat": 2,
#     "n_envs": 24,
#     "train_steps": 800_000,
#     "eval_interval": 5_000 * 24,
#     "num_init_states": 24,
#     "eval_episodes": 32,
#     "near_optimal_score": 250,
#     "sub_optimal_score": 175,
#     "save_path": "./lunar_lander_density_results",
# }

lunarlander_config = {
    "env_type": "lunarlander",
    "num_densities": 5,
    "density_start": 3.0,
    "density_stop": 7.0,
    "n_repeat": 8,
    "n_envs": 16,
    "train_steps": 1_500_000,
    "eval_interval": 10_000 * 16,
    "num_init_states": 16,
    "eval_episodes": 32,
    "near_optimal_score": 250,
    "sub_optimal_score": 175,
    "save_path": "./lunar_lander_density_results",
}
